2025-04-19 06:56:10,726 ERROR frappe Unable to load translations
Site: carosite
Form Dict: {}
Traceback (most recent call last):
  File "/home/huyb/frappe-bench/apps/frappe/frappe/utils/caching.py", line 65, in wrapper
    return _cache[func][args_key]
           ~~~~~~~~~~~~^^^^^^^^^^
KeyError: ((), <object object at 0x7ff9867c4f80>, frozenset({('_ensure_on_bench', True)}))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/huyb/frappe-bench/apps/frappe/frappe/translate.py", line 174, in get_all_translations
    return frappe.cache.hget(MERGED_TRANSLATION_KEY, lang, generator=_merge_translations)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 246, in hget
    value = generator()
            ^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/translate.py", line 162, in _merge_translations
    all_translations.update(get_translations_from_apps(lang))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/translate.py", line 189, in get_translations_from_apps
    for app in apps or frappe.get_installed_apps(_ensure_on_bench=True):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/utils/caching.py", line 71, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/__init__.py", line 1247, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/database/database.py", line 1118, in get_global
    return self.get_default(key, user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/database/database.py", line 1122, in get_default
    d = self.get_defaults(key, parent)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/database/database.py", line 1138, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/defaults.py", line 249, in get_defaults_for
    .run(as_dict=True)
     ^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 80, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/database/database.py", line 260, in sql
    self.execute_query(query, values)
  File "/home/huyb/frappe-bench/apps/frappe/frappe/database/database.py", line 355, in execute_query
    return self._cursor.execute(query, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 1206, in read
    self._read_result_packet(first_packet)
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 1283, in _read_result_packet
    self._read_rowdata_packet()
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 1330, in _read_rowdata_packet
    packet = self.connection._read_packet()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1412, 'Table definition has changed, please retry transaction')
2025-04-19 06:56:11,003 ERROR frappe Unable to load translations
Site: carosite
Form Dict: {}
Traceback (most recent call last):
  File "/home/huyb/frappe-bench/apps/frappe/frappe/utils/caching.py", line 65, in wrapper
    return _cache[func][args_key]
           ~~~~~~~~~~~~^^^^^^^^^^
KeyError: ((), <object object at 0x7ff9867c4f80>, frozenset({('_ensure_on_bench', True)}))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/huyb/frappe-bench/apps/frappe/frappe/translate.py", line 174, in get_all_translations
    return frappe.cache.hget(MERGED_TRANSLATION_KEY, lang, generator=_merge_translations)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 246, in hget
    value = generator()
            ^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/translate.py", line 162, in _merge_translations
    all_translations.update(get_translations_from_apps(lang))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/translate.py", line 189, in get_translations_from_apps
    for app in apps or frappe.get_installed_apps(_ensure_on_bench=True):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/utils/caching.py", line 71, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/__init__.py", line 1247, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/database/database.py", line 1118, in get_global
    return self.get_default(key, user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/database/database.py", line 1122, in get_default
    d = self.get_defaults(key, parent)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/database/database.py", line 1138, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/defaults.py", line 249, in get_defaults_for
    .run(as_dict=True)
     ^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 80, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/database/database.py", line 260, in sql
    self.execute_query(query, values)
  File "/home/huyb/frappe-bench/apps/frappe/frappe/database/database.py", line 355, in execute_query
    return self._cursor.execute(query, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 1206, in read
    self._read_result_packet(first_packet)
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 1283, in _read_result_packet
    self._read_rowdata_packet()
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 1330, in _read_rowdata_packet
    packet = self.connection._read_packet()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1412, 'Table definition has changed, please retry transaction')
2025-04-19 06:56:11,216 ERROR frappe Unable to load translations
Site: carosite
Form Dict: {}
Traceback (most recent call last):
  File "/home/huyb/frappe-bench/apps/frappe/frappe/utils/caching.py", line 65, in wrapper
    return _cache[func][args_key]
           ~~~~~~~~~~~~^^^^^^^^^^
KeyError: ((), <object object at 0x7ff9867c4f80>, frozenset({('_ensure_on_bench', True)}))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/huyb/frappe-bench/apps/frappe/frappe/translate.py", line 174, in get_all_translations
    return frappe.cache.hget(MERGED_TRANSLATION_KEY, lang, generator=_merge_translations)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 246, in hget
    value = generator()
            ^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/translate.py", line 162, in _merge_translations
    all_translations.update(get_translations_from_apps(lang))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/translate.py", line 189, in get_translations_from_apps
    for app in apps or frappe.get_installed_apps(_ensure_on_bench=True):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/utils/caching.py", line 71, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/__init__.py", line 1247, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/database/database.py", line 1118, in get_global
    return self.get_default(key, user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/database/database.py", line 1122, in get_default
    d = self.get_defaults(key, parent)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/database/database.py", line 1138, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/defaults.py", line 249, in get_defaults_for
    .run(as_dict=True)
     ^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 80, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/apps/frappe/frappe/database/database.py", line 260, in sql
    self.execute_query(query, values)
  File "/home/huyb/frappe-bench/apps/frappe/frappe/database/database.py", line 355, in execute_query
    return self._cursor.execute(query, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 1206, in read
    self._read_result_packet(first_packet)
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 1283, in _read_result_packet
    self._read_rowdata_packet()
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 1330, in _read_rowdata_packet
    packet = self.connection._read_packet()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/huyb/frappe-bench/env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1412, 'Table definition has changed, please retry transaction')
